run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - errcheck
    - staticcheck
    - revive
    - govet
    - unconvert
    - misspell
    - ineffassign
    - bodyclose
    - gocritic
    - sqlclosecheck
    - nilerr

linters-settings:
  govet:
    check-shadowing: true
  revive:
    rules:
      - name: package-comments
        disabled: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - wrapperFunc
      - rangeValCopy

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
